config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  resources :recipes
  resources :recipe_types
  resources :cuisines
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes
  validates :name, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :recipe_type
  belongs_to :cuisine

  validates :title, :cuisine, :difficulty, :cook_time,
            :ingredients, :cook_method, presence: true

  def cook_time_min
    "#{cook_time} minutos"
  end
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes
  validates :name, presence: { message: 'Você deve informar o nome do'\
                                        ' tipo de receita' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def show
    @cuisine = Cuisine.find(params[:id])
  end

  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.new(params.require(:cuisine).permit(:name))

    if @cuisine.save
      redirect_to @cuisine
    else
      flash[:alert] = 'Você deve informar o nome da cozinha'
      render :new
    end
  end

  def edit
    @cuisine = Cuisine.find(params[:id])
  end

  def update
    @cuisine = Cuisine.find(params[:id])

    if @cuisine.update(cuisine_params)
      redirect_to @cuisine
    else
      flash[:alert] = 'Você deve editar a receita' 
      render :new
    end
  end

  private

  def cuisine_params
    params.require(:cuisine).permit(:name )
  end

end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  def show
    @recipe_type = RecipeType.find(params[:id])
  end

  def new
    @recipe_type = RecipeType.new
  end

  def create
    @recipe_type = RecipeType.new(params.require(:recipe_type).permit(:name))

    if @recipe_type.save
      redirect_to @recipe_type
    else
      flash[:alert] = 'Você deve informar o nome do tipo de receita'
      render :new
    end    
  end

  def edit
    @recipe_type = RecipeType.find(params[:id])
  end

  def update
    @recipe_type = RecipeType.find(params[:id])

    if @recipe_type.update(recipe_type_params)
      redirect_to @recipe_type
    else
      flash[:alert] = 'Você deve editar o tipo da receita' 
      render :new
    end
  end

  private

  def recipe_type_params
    params.require(:recipe_type).permit(:name )
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
    @difficulties = ["Facil", "Medio", "Dificil"]
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to @recipe
    else
      flash[:alert] = 'Você deve informar todos os dados da receita'
      @recipe_types = RecipeType.all
      @cuisines = Cuisine.all
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
    @difficulties = ["Facil", "Medio", "Dificil"]
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      flash[:alert] = 'Você deve informar todos os dados da receita'
      @recipe_types = RecipeType.all
      @cuisines = Cuisine.all
      render :new
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :recipe_type_id, :cuisine_id,
     :difficulty, :cook_time, :ingredients,
     :cook_method)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuisines/edit.html.erb
<div class="container pt-4">
	<h2>Editar tipo de Cozinha</h2>
	<%= form_for @cuisine do |f| %>
	<%= f.label :name, 'Nome' %>
	<%= f.text_field :name %>
	<%= f.submit 'Enviar' %>
	<% end %>
</div>

app/views/cuisines/new.html.erb
<div class="container pt-4">
	<h2>Cadastrar tipo de Cozinha</h2>
	<%= form_for @cuisine do |f| %>
	<%= f.label :name, 'Nome' %>
	<%= f.text_field :name %>
	<%= f.submit 'Enviar' %>
	<% end %>
</div>

app/views/cuisines/show.html.erb
<div class="container pt-4">
	<h1><%= @cuisine.name %></h1>
	<%= link_to 'Voltar', root_path, class: "btn btn-sm btn-outline-secondary" %>							
	<%= link_to 'Editar', edit_cuisine_path, class: "btn btn-sm btn-outline-secondary" %>							
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small special-color-dark pt-4">

    <!-- Footer Elements -->
    <div class="container">

      <!-- Social buttons -->
      <ul class="list-unstyled list-inline text-center">
        <li class="list-inline-item">
          <a class="btn-floating btn-fb mx-1">
            <i class="fab fa-facebook-f"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-tw mx-1">
            <i class="fab fa-twitter"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-gplus mx-1">
            <i class="fab fa-google-plus-g"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-li mx-1">
            <i class="fab fa-linkedin-in"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-dribbble mx-1">
            <i class="fab fa-dribbble"> </i>
          </a>
        </li>
      </ul>
      <!-- Social buttons -->

    </div>
    <!-- Footer Elements -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href="#"> Cookbook </a>
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->

app/views/layouts/_header.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <img src="/assets/cooking.png" class="mr-2">
        <strong class="pt-2">Cookbook</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>

<body>
  <%= render 'layouts/header' %>
  <%= flash[:alert] %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/recipe_types/edit.html.erb
<div class="container pt-4">
<h2>Editar Tipo de Receita</h2>
	<%= form_for @recipe_type do |f| %>
	<%= f.label :name, 'Nome' %>
	<%= f.text_field :name %>
	<%= f.submit 'Enviar' %>
	<% end %>
</div>

app/views/recipe_types/new.html.erb
<div class="container pt-4">
<h2>Cadastrar tipo de Receita</h2>
	<%= form_for @recipe_type do |f| %>
	<%= f.label :name, 'Nome' %>
	<%= f.text_field :name %>
	<%= f.submit 'Enviar' %>
	<% end %>
</div>

app/views/recipe_types/show.html.erb
<div class="container pt-4">
	<h1><%= @recipe_type.name %></h1>
	<%= link_to 'Voltar', root_path, class: "btn btn-sm btn-outline-secondary" %>							
	<%= link_to 'Editar', edit_recipe_type_path, class: "btn btn-sm btn-outline-secondary" %>							
</div>

app/views/recipes/_form.html.erb
<div class="container pt-4 pb-3">
  <h3> Cadastrar Nova Receita </h3>
  <%= form_for @recipe do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :recipe_type_id, 'Tipo da Receita' %>
    <%= f.collection_select :recipe_type_id, @recipe_types, :id, :name, {}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :cuisine_id, 'Cozinha' %>
    <%= f.collection_select :cuisine_id, @cuisines, :id, :name, {}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :difficulty, 'Dificuldade' %>
    <%= f.select :difficulty, @difficulties, {}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :cook_time, 'Tempo de Preparo' %>
    <%= f.number_field :cook_time, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :ingredients, 'Ingredientes' %>
    <%= f.text_area :ingredients, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :cook_method, 'Como Preparar' %>
    <%= f.text_area :cook_method, {class: "form-control"} %>
  </div>
  <%= f.submit 'Enviar' %>
  <% end %>
</div>

app/views/recipes/edit.html.erb
<%= render partial: 'form' %>

app/views/recipes/index.html.erb
<main role="main">

	<section class="jumbotron text-center">
		<div class="container">
			<h1 class="jumbotron-heading">CookBook</h1>
			<p class="lead text-muted">Bem-vindo ao maior livro de receitas online</p>
			<p>
				<%= link_to 'Enviar uma receita', new_recipe_path, class: "btn btn-primary my-2" %>
				<%= link_to 'Cadastrar tipo de receita', new_recipe_type_path, class: "btn btn-secondary my-2" %>
				<%= link_to 'Cadastrar cozinha', new_cuisine_path, class: "btn btn-secondary my-2" %>
			</p>
		</div>
	</section>

	<div class="album py-5 bg-light">
		<div class="container">
			<div class="row">
				<% @recipes.each do |recipe| %>			
				<div class="col-md-4">
					<div class="card mb-4 box-shadow">
						<img class="card-img-top" src="/assets/receita.jpg" alt="Card image cap">
						<div class="card-body">
							<p class="card-text">
								<%= link_to recipe.title, recipe %>
								<br/>
								<%= recipe.recipe_type.name %>
								<br/>
								<%= recipe.cuisine.name %>
								<br/>
								<%= recipe.difficulty %>
							</p>
							<div class="d-flex justify-content-between align-items-center">
								<div>
									<%= link_to 'Ver Detalhes', recipe_path(recipe.id), :class => "btn btn-sm btn-outline-secondary" %>
									<%= link_to 'Editar', edit_recipe_path(recipe.id), :class => "btn btn-sm btn-outline-secondary" %>
								</div>
								<small class="text-muted"><%= recipe.cook_time_min %></small>
							</div>
						</div>
					</div>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</main>

app/views/recipes/new.html.erb
<%= render partial: 'form' %>

app/views/recipes/show.html.erb
<div class="container pt-4">
	<div class="row">
		<div class="col-md-9">
			<div class="panel panel-default">
				<div class="panel-body">
					<div class="row">
						<div class="col-md-4 text-center">
							<img class="img-thumbnail" src="/assets/receita.jpg">
						</div>
						<div class="col-md-8">
							<div class="row">
								<div class="col-md-12">
									<h1 class="only-bottom-margin"><%= @recipe.title %></h1>
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">
									<span class="text-muted">Tipo de receita:</span> <%= @recipe.recipe_type.name %><br>
									<span class="text-muted">Tipo de cozinha:</span><%= @recipe.cuisine.name %><br>
									<span class="text-muted">Dificuldade:</span> <%= @recipe.difficulty %><br><br>
									<h3>Ingredientes</h3>
									<span class="text-muted">Ingredientes:</span> <%= @recipe.ingredients %></ %><br><br>
									<h3>Como Preparar</h3>
									<span class="text-muted">Modo de preparo:</span> <%= @recipe.cook_method %><br><br>
									<span class="text-muted">Tempo de preparo:</span> <%= @recipe.cook_time_min %><br><br>
									<small class="text-muted">Criado em: <%= @recipe.created_at.strftime("%d.%m.%Y") %></small>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<hr>
							<%= link_to 'Editar', edit_recipe_path(@recipe), class: "btn btn-sm btn-outline-secondary" %>
							<%= link_to 'Voltar', root_path, class: "btn btn-sm btn-outline-secondary" %>							
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>